### ISSUE TITLE
themes made hideous

### ISSUE THREAD

**Issue by TimOgilvy** [terryweiss/docstrap#101]
I'm not sure why, but the Bootswatch themes have been heavily modified to use all the gaudy colours.

These *were* tasteful themes.

It's not simply possible to restore a theme to its original Bootswatch code, as significant docstrap features go missing in the process. 

Two questions:
1. Why?
2. How do I revert them to the tasteful colours they came with originally without breaking docstrap?

**Comment by TimOgilvy** [comment]
Is it possible that these themes were just genuinely ugly before bootstrap 3? 

I'm referencing the current versions visible at https://bootswatch.com/  I realise now may not match the version of bootstrap used in dosctrap.

**Comment by terryweiss** [comment]
Not sure what you are seeing, but this is what they look like:
+ [Amelia](http://terryweiss.github.io/docstrap/themes/amelia)
+ [Cerulean](http://terryweiss.github.io/docstrap/themes/cerulean)
+ [Cosmo](http://terryweiss.github.io/docstrap/themes/cosmo)
+ [Cyborg](http://terryweiss.github.io/docstrap/themes/cyborg)
+ [Flatly](http://terryweiss.github.io/docstrap/themes/flatly)
+ [Journal](http://terryweiss.github.io/docstrap/themes/journal)
+ [Readable](http://terryweiss.github.io/docstrap/themes/readable)
+ [Simplex](http://terryweiss.github.io/docstrap/themes/simplex)
+ [Slate](http://terryweiss.github.io/docstrap/themes/slate)
+ [Spacelab](http://terryweiss.github.io/docstrap/themes/spacelab)
+ [Spruce](http://terryweiss.github.io/docstrap/themes/spruce)
+ [Superhero](http://terryweiss.github.io/docstrap/themes/superhero)
+ [United](http://terryweiss.github.io/docstrap/themes/united)

**Comment by TimOgilvy** [comment]
Yes, that's what they look like in docstrap.  But lets take the original bootswatch versions and compare:

In docstrap the menus are solid filled instead of white, and all the headings are in gaudy colours instead of the standard colours in the bootswatch versions.

 I realise there's a setting for the navbar inversion, but it doesn't stop the menus being filled, and I can't see away to avoid hypercolourised titles etc.

docstrap: [Flatly](http://terryweiss.github.io/docstrap/themes/flatly)
bootswatch [Flatly](https://bootswatch.com/flatly/)

docstrap: [Cosmo](http://terryweiss.github.io/docstrap/themes/cosmo)
bootswatch [Cosmo](https://bootswatch.com/cosmo/)

**Comment by terryweiss** [comment]
Take a look at conf.json What you are seeing are the inverse nav colors, which are legit bootstrap classes. If you don't like them change this in conf.json

inverseNav Bootstrap navbars come in two flavors, regular and inverse where inverse is generally higher contrast. Set this to true to use the inverse header.

**Comment by TimOgilvy** [comment]
As per my previous comment above "I realise there's a setting for the navbar inversion, but it doesn't stop the menus being filled, and I can't see away to avoid hypercolourised titles etc."

Yes. I have used the inverseNav setting in conf.json. All it does is prevent the class "navbar-inverse" from being added to the navbar.  Everything else stays the same. The menus are still dark-filled, and the headings are still coloured.

**Comment by terryweiss** [comment]
All styling happens in the templates for the various visual components and you can modify it to meet your needs. docstrap was designed to be high contrast and not intended to address everyone's aesthetic sense.  A PR would be welcomed.

**Comment by TimOgilvy** [comment]
Thanks. Hideous was a strong word and I feel quite bad about it. Comes across as plain rude. Sorry about that and thanks for responding. I'm finding my way around the templates slowly :)
