### ISSUE TITLE
Copy static files during generation

### ISSUE THREAD

**Issue by esatterwhite** [terryweiss/docstrap#78]
JSdoc added support for [copying static](https://github.com/jsdoc3/jsdoc/issues/393) files of specified directories so they can be included in tutorials.  This happens in the publish function, which has not made it into the docstrap theme

**Comment by tswaters** [comment]
I can do this.  It should work with both 3.2.2 and 3.3.0 - however, there are a few changes to jsdoc's filter function - notably jsdoc3/jsdoc#484 that won't apply to the older version.
